# Generated by Django 3.2.5 on 2021-07-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('passport', models.BooleanField(default=False)),
                ('provider', models.CharField(default='DEFAULT', max_length=20)),
                ('token', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('IATA', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
