# Generated by Django 3.1.12 on 2021-08-26 13:36

from django.db import migrations, models
import djongo.models.fields
import server.models.dog_model


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('motivation', models.CharField(max_length=500)),
                ('resume', models.CharField(max_length=1000)),
                ('departure', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('departureDate', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('dog', djongo.models.fields.EmbeddedField(model_container=server.models.dog_model.AbstractDog)),
                ('userEmail', models.CharField(max_length=100)),
            ],
        ),
    ]
