# Generated by Django 3.1.12 on 2021-09-05 14:40

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
    ]
