name: Dokcer Publish

on:
  push:
    branches: [ deploy ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/django-petch

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/django-petch
